### ISSUE TITLE
Type error occured while trying to run simulation

### ISSUE THREAD

**Issue by logan881** [zanoni-mbdyn/blendyn#50]
An error popped up when I tried to run simulation after selecting input file.

```
Python: Traceback (most recent call last):
  File "C:\Users\Xiang\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blendyn-master\blendyn.py", line 1328, in invoke
    return self.execute(context)
  File "C:\Users\Xiang\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blendyn-master\blendyn.py", line 1255, in execute
    self.timer = context.window_manager.event_timer_add(0.5, context.window)
TypeError: WindowManager.event_timer_add(): required parameter "window" to be a keyword argument!

location: <unknown location>:-1
```

Conditions to reproduce:
Ubuntu 20.04.4
MBDyn 1.7.3
Current version of Blendyn
Blender 3.1.2
Python 3.10.4
All dependencies of MBDyn, Blender and Blendyn installed

Steps to reproduce:
1.Save an [example](https://www.sky-engin.jp/en/MBDynTutorial/chap06/chap06.html) as txt file.
2.Select the file as input file.
3.click `Run Simulation`.

**Comment by zanoni-mbdyn** [comment]
Hi @logan881, thank you for the report. I'm looking into the issue.

**Comment by zanoni-mbdyn** [comment]
Should be fixed now, in `bugfix`. If you can, please test and report.

**Comment by logan881** [comment]
Hello,it doesn't show the message now.But after clicking `run simulation`,nothing will change.I can't get `.mov` or `.log` or any new files.I record a video of my steps,and it may help you understand my problem.
[video](https://www.youtube.com/watch?v=BFGQ2BS9ino&ab_channel=%E7%84%A1%E7%B3%96%E7%B6%A0%E8%8C%B6)

**Comment by zanoni-mbdyn** [comment]
Hi @logan881, thank you for the video. Can you start Blender from a terminal (for example, the Powershell) and send me the output while trying to run the MBDyn simulation?

**Comment by zanoni-mbdyn** [comment]
Closing for inactivity
