### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by rockstorm101** [zanoni-mbdyn/blendyn#56]
I get the error seen ~~on the image~~ below when hitting the "Animate scene" button.
```
Traceback (most recent call last):
  File "/home/rock/.config/blender/3.6/scripts/addons/blendyn-master/blendyn.py", line 1499, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.config/blender/3.6/scripts/addons/blendyn-master/blendyn.py", line 1488, in execute
    ret_val = set_motion_paths_mov(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.config/blender/3.6/scripts/addons/blendyn-master/baselib.py", line 1066, in set_motion_paths_mov
    rw_mov = np.array(next(reader_mov)).astype(np.float)
                                               ^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
Error: Python: Traceback (most recent call last):
  File "/home/rock/.config/blender/3.6/scripts/addons/blendyn-master/blendyn.py", line 1499, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.config/blender/3.6/scripts/addons/blendyn-master/blendyn.py", line 1488, in execute
    ret_val = set_motion_paths_mov(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.config/blender/3.6/scripts/addons/blendyn-master/baselib.py", line 1066, in set_motion_paths_mov
    rw_mov = np.array(next(reader_mov)).astype(np.float)
                                               ^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

-- System Information:
Debian 13
Blender 3.6.2
Python 3.11.6
NumPy 1.24.2
Blendyn: commit https://github.com/zanoni-mbdyn/blendyn/commit/ee0853d5c4f79cb3f35c570d0e6558bcc457492a

-- Edit:
Swapped error image with error text for (better?) readability.

**Comment by zanoni-mbdyn** [comment]
Should be fixed in [bugfix](https://github.com/zanoni-mbdyn/blendyn/tree/bugfix) now.

**Comment by rockstorm101** [comment]
Hi @zanoni-mbdyn, thanks for the quick fix. I can confirm the issue is solved on the bugfix branch now.

**Comment by zanoni-mbdyn** [comment]
Good. Thank you, I will merge in master and close the issue.
